"""add name and status

Revision ID: 4f4ebe122f90
Revises: 13e9bcccc4ed
Create Date: 2021-11-08 01:25:45.714319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4ebe122f90'
down_revision = '13e9bcccc4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('name', sa.String(), nullable=True))
    op.add_column('season', sa.Column('status', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'season', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'season', type_='unique')
    op.drop_column('season', 'status')
    op.drop_column('season', 'name')
    # ### end Alembic commands ###
