"""create sensors table

Revision ID: bcc73272ad13
Revises: 
Create Date: 2021-11-30 10:02:46.882397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc73272ad13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sensor_name', sa.NullType(), nullable=True),
    sa.Column('sensor_status', sa.NullType(), nullable=True),
    sa.Column('sensor_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('type_connection', sa.String(length=20), nullable=True),
    sa.Column('port_address', sa.String(length=20), nullable=True),
    sa.Column('port_speed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor')
    op.drop_table('history')
    # ### end Alembic commands ###
